export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";
export const AUTH_LOGOUT_REQUEST = "AUTH_LOGOUT_REQUEST";

export const CREATE_BLOG_REQUEST = "CREATE_BLOG_REQUEST";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";
export const CREATE_BLOG_FAIL = "CREATE_BLOG_FAIL";
export const CREATE_BLOG_RESET = "CREATE_BLOG_FAIL";

export const FETCH_ALL_ARTICLES_REQUEST = "FETCH_ALL_ARTICLES_REQUEST";
export const FETCH_ALL_ARTICLES_SUCCESS = "FETCH_ALL_ARTICLES_SUCCESS";
export const FETCH_ALL_ARTICLES_FAIL = "FETCH_ALL_ARTICLES_FAIL";

export const FETCH_BLOG_REQUEST = "FETCH_BLOG_REQUEST";
export const FETCH_BLOG_SUCCESS = "FETCH_BLOG_SUCCESS";
export const FETCH_BLOG_FAIL = "FETCH_BLOG_FAIL";

export const PUBLISH_ARTICLE_REQUEST = "PUBLISH_ARTICLE_REQUEST";
export const PUBLISH_ARTICLE_SUCCESS = "PUBLISH_ARTICLE_SUCCESS";
export const PUBLISH_ARTICLE_FAIL = "PUBLISH_ARTICLE_FAIL";

export const UNPUBLISH_ARTICLE_REQUEST = "UNPUBLISH_ARTICLE_REQUEST";
export const UNPUBLISH_ARTICLE_SUCCESS = "UNPUBLISH_ARTICLE_SUCCESS";
export const UNPUBLISH_ARTICLE_FAIL = "UNPUBLISH_ARTICLE_FAIL";

export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAIL = "FETCH_CATEGORIES_FAIL";

export const FETCH_TAGS_REQUEST = "FETCH_TAGS_REQUEST";
export const FETCH_TAGS_SUCCESS = "FETCH_TAGS_SUCCESS";
export const FETCH_TAGS_FAIL = "FETCH_TAGS_FAIL";

export const UPDATE_ARTICLE_REQUEST = "UPDATE_ARTICLE_REQUEST";
export const UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";
export const UPDATE_ARTICLE_FAIL = "UPDATE_ARTICLE_FAIL";
export const UPDATE_ARTICLE_RESET = "UPDATE_ARTICLE_RESET";

export const ADD_TAG_REQUEST = "ADD_TAG_REQUEST";
export const ADD_TAG_SUCCESS = "ADD_TAG_SUCCESS";
export const ADD_TAG_FAIL = "ADD_TAG_FAIL";

export const ADD_TAGS_BULK_REQUEST = "ADD_TAGS_BULK_REQUEST";
export const ADD_TAGS_BULK_SUCCESS = "ADD_TAGS_BULK_SUCCESS";
export const ADD_TAGS_BULK_FAIL = "ADD_TAGS_BULK_FAIL";

export const GET_ARTICLES_BY_CATEGORIES_REQUEST =
  "GET_ARTICLES_BY_CATEGORIES_REQUEST";
export const GET_ARTICLES_BY_CATEGORIES_SUCCESS =
  "GET_ARTICLES_BY_CATEGORIES_SUCCESS";
export const GET_ARTICLES_BY_CATEGORIES_FAIL =
  "GET_ARTICLES_BY_CATEGORIES_FAIL";

export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";

export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";
export const ADD_CATEGORY_RESET = "ADD_CATEGORY_RESET";

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";
export const DELETE_CATEGORY_RESET = "DELETE_CATEGORY_RESET";
