export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";

export const CREATE_USER_REQUEST  = "CREATE_USER_REQUEST"
export const CREATE_USER_SUCCESS  = "CREATE_USER_SUCCESS"
export const CREATE_USER_FAIL  = "CREATE_USER_FAIL"

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST" 
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS" 
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL" 

export const MAKE_ADMIN_REQUEST = "MAKE_ADMIN_REQUEST"
export const MAKE_ADMIN_SUCCESS = "MAKE_ADMIN_SUCCESS"
export const MAKE_ADMIN_FAIL = "MAKE_ADMIN_FAIL"

export const DEMOTE_ADMIN_REQUEST = "DEMOTE_ADMIN_REQUEST"
export const DEMOTE_ADMIN_SUCCESS = "DEMOTE_ADMIN_SUCCESS"
export const DEMOTE_ADMIN_FAIL = "DEMOTE_ADMIN_FAIL"

export const ACTIVATE_USER_REQUEST = "ACTIVATE_USER_REQUEST"
export const ACTIVATE_USER_SUCCESS = "ACTIVATE_USER_SUCCESS"
export const ACTIVATE_USER_FAIL = "ACTIVATE_USER_FAIL"

export const DEACTIVATE_USER_REQUEST = "DEACTIVATE_USER_REQUEST"
export const DEACTIVATE_USER_SUCCESS = "DEACTIVATE_USER_SUCCESS"
export const DEACTIVATE_USER_FAIL = "DEACTIVATE_USER_FAIL"
